/**
 * Created by miracle on 2016/8/13.
 */
export const TEST ='TEST';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGINING = 'LOGINING';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTERING = 'REGISTERING';

export const FETCH_PERSON ='FETCH_PERSON';
export const FETCH_PERSON_SUCCESS = 'FETCH_PERSON_SUCCESS';
export const FETCH_PERSON_FAIL = 'FETCH_PERSON_FAIL';

export const FETCH_DATASET = 'FETCH_DATASET';
export const FETCH_DATASET_SUCCESS = 'FETCH_DATASET_SUCCESS';
export const FETCH_DATASET_FAIL = 'FETCH_DATASET_FAIL';

export const FETCH_MOOD = 'FETCH_MOOD';
export const FETCH_MOOD_SUCCESS = 'FETCH_MOOD_SUCCESS';
export const FETCH_MOOD_FAIL = 'FETCH_MOOD_FAIL';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';
export const COMMENT_AFTER_LOGIN = 'COMMENT_AFTER_LOGIN';